<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.obm.network</groupId>
    <artifactId>omd-network-parent</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>

    <name>OMD Network Plugins</name>
    <description>Agregador Maven para os plugins OBM-Core, OBM-Lobby, OBM-Inventory e OBM-UHC.</description>

    <properties>
        <java.version>17</java.version>
        <spigot.api.version>1.20.4-R0.1-SNAPSHOT</spigot.api.version>
        <placeholderapi.version>2.11.6</placeholderapi.version>
        <decentholograms.version>2.8.8</decentholograms.version>
    </properties>

    <modules>
        <module>OBM-Core</module>
        <module>OBM-Lobby</module>
        <module>OBM-Inventory</module>
        <module>OBM-UHC</module>
        <module>OBM-SMP</module>
    </modules>

    <repositories>
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>placeholderapi</id>
            <url>https://repo.extendedclip.com/content/repositories/placeholderapi/</url>
        </repository>
        <repository>
            <id>codemc-repo</id>
            <url>https://repo.codemc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>papermc-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
    </repositories>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.10.1</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
