CREATE TABLE IF NOT EXISTS tierspace_arenas (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  mode VARCHAR(32) NOT NULL DEFAULT 'sword',
  world VARCHAR(64) NOT NULL DEFAULT 'TierSpace',
  pos1_x DOUBLE PRECISION NOT NULL DEFAULT 0,
  pos1_y DOUBLE PRECISION NOT NULL DEFAULT 64,
  pos1_z DOUBLE PRECISION NOT NULL DEFAULT 0,
  pos1_yaw REAL NOT NULL DEFAULT 0,
  pos1_pitch REAL NOT NULL DEFAULT 0,
  pos2_x DOUBLE PRECISION NOT NULL DEFAULT 0,
  pos2_y DOUBLE PRECISION NOT NULL DEFAULT 64,
  pos2_z DOUBLE PRECISION NOT NULL DEFAULT 10,
  pos2_yaw REAL NOT NULL DEFAULT 180,
  pos2_pitch REAL NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT true,
  auto_reset BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tierspace_arenas_mode ON tierspace_arenas (mode);
CREATE INDEX IF NOT EXISTS idx_tierspace_arenas_enabled ON tierspace_arenas (enabled);
