name: OBM-Lobby
main: com.obm.network.lobby.OBMLobbyPlugin
version: 1.0
api-version: 1.20
author: Obmar
description: Lobby do MineSpace

depend:
  - OBM-Core

softdepend:
  - PlaceholderAPI
  - DecentHolograms
  - OBM-SMP
  - OBM-TierSpace

permissions:
  obm.lobby:
    description: Voltar ao lobby (/lobby)
    default: false
  obm.menu:
    description: Abrir menu principal (/menu)
    default: false

commands:
  lobby:
    description: Voltar para o lobby
    usage: /lobby
    permission: obm.lobby

  menu:
    description: Abrir menu principal
    usage: /menu
    permission: obm.menu
